apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: by-subdomain-backend-access-ingress
  namespace: default
spec:
  virtualhost:
    fqdn: api.iconrepo.internal
  routes:
    - conditions:
      - prefix: /
      services:
        - name: iconrepo-backend
          port: 8080
